#define ORGAN_SLOT_SCANNER "scanner"
#define ORGAN_SLOT_BRAIN_NIF "nif"
#define ORGAN_SLOT_NIPPLES "nipples"
#define ORGAN_ERP_LIST list(ORGAN_SLOT_PENIS, ORGAN_SLOT_WOMB, ORGAN_SLOT_VAGINA, ORGAN_SLOT_TESTICLES, ORGAN_SLOT_BREASTS, ORGAN_SLOT_ANUS, ORGAN_SLOT_NIPPLES, ORGAN_SLOT_BUTT, ORGAN_SLOT_BELLY)
#define ORGAN_SLOT_WINGS "wings"
